// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mkk_basis/rest_api/internal/app/core/entities/auth-entities"
	"mkk_basis/rest_api/internal/app/core/entities/users-entities"
	"mkk_basis/rest_api/internal/app/core/services/auth-service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(context1 context.Context, loginRequest *auth_entities.LoginRequest) (*users_entities.UserResponse, *auth_service.TokenPair, error) {
	ret := _mock.Called(context1, loginRequest)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *users_entities.UserResponse
	var r1 *auth_service.TokenPair
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth_entities.LoginRequest) (*users_entities.UserResponse, *auth_service.TokenPair, error)); ok {
		return returnFunc(context1, loginRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth_entities.LoginRequest) *users_entities.UserResponse); ok {
		r0 = returnFunc(context1, loginRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth_entities.LoginRequest) *auth_service.TokenPair); ok {
		r1 = returnFunc(context1, loginRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*auth_service.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *auth_entities.LoginRequest) error); ok {
		r2 = returnFunc(context1, loginRequest)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - context1 context.Context
//   - loginRequest *auth_entities.LoginRequest
func (_e *MockAuthService_Expecter) Login(context1 interface{}, loginRequest interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", context1, loginRequest)}
}

func (_c *MockAuthService_Login_Call) Run(run func(context1 context.Context, loginRequest *auth_entities.LoginRequest)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth_entities.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(*auth_entities.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(userResponse *users_entities.UserResponse, tokenPair *auth_service.TokenPair, err error) *MockAuthService_Login_Call {
	_c.Call.Return(userResponse, tokenPair, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context1 context.Context, loginRequest *auth_entities.LoginRequest) (*users_entities.UserResponse, *auth_service.TokenPair, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccess provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshAccess(context1 context.Context, s string) (*auth_service.AccessToken, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccess")
	}

	var r0 *auth_service.AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth_service.AccessToken, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth_service.AccessToken); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_service.AccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccess'
type MockAuthService_RefreshAccess_Call struct {
	*mock.Call
}

// RefreshAccess is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockAuthService_Expecter) RefreshAccess(context1 interface{}, s interface{}) *MockAuthService_RefreshAccess_Call {
	return &MockAuthService_RefreshAccess_Call{Call: _e.mock.On("RefreshAccess", context1, s)}
}

func (_c *MockAuthService_RefreshAccess_Call) Run(run func(context1 context.Context, s string)) *MockAuthService_RefreshAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshAccess_Call) Return(accessToken *auth_service.AccessToken, err error) *MockAuthService_RefreshAccess_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *MockAuthService_RefreshAccess_Call) RunAndReturn(run func(context1 context.Context, s string) (*auth_service.AccessToken, error)) *MockAuthService_RefreshAccess_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(context1 context.Context, userRequest *users_entities.UserRequest) (*users_entities.UserResponse, error) {
	ret := _mock.Called(context1, userRequest)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *users_entities.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users_entities.UserRequest) (*users_entities.UserResponse, error)); ok {
		return returnFunc(context1, userRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users_entities.UserRequest) *users_entities.UserResponse); ok {
		r0 = returnFunc(context1, userRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *users_entities.UserRequest) error); ok {
		r1 = returnFunc(context1, userRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - context1 context.Context
//   - userRequest *users_entities.UserRequest
func (_e *MockAuthService_Expecter) Register(context1 interface{}, userRequest interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", context1, userRequest)}
}

func (_c *MockAuthService_Register_Call) Run(run func(context1 context.Context, userRequest *users_entities.UserRequest)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *users_entities.UserRequest
		if args[1] != nil {
			arg1 = args[1].(*users_entities.UserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(userResponse *users_entities.UserResponse, err error) *MockAuthService_Register_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context1 context.Context, userRequest *users_entities.UserRequest) (*users_entities.UserResponse, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccess provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ValidateAccess(s string) (*auth_service.Claims, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccess")
	}

	var r0 *auth_service.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth_service.Claims, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth_service.Claims); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_service.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_ValidateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccess'
type MockAuthService_ValidateAccess_Call struct {
	*mock.Call
}

// ValidateAccess is a helper method to define mock.On call
//   - s string
func (_e *MockAuthService_Expecter) ValidateAccess(s interface{}) *MockAuthService_ValidateAccess_Call {
	return &MockAuthService_ValidateAccess_Call{Call: _e.mock.On("ValidateAccess", s)}
}

func (_c *MockAuthService_ValidateAccess_Call) Run(run func(s string)) *MockAuthService_ValidateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_ValidateAccess_Call) Return(claims *auth_service.Claims, err error) *MockAuthService_ValidateAccess_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockAuthService_ValidateAccess_Call) RunAndReturn(run func(s string) (*auth_service.Claims, error)) *MockAuthService_ValidateAccess_Call {
	_c.Call.Return(run)
	return _c
}
