// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	tasks_entities "mkk_basis/rest_api/internal/app/core/entities/tasks-entities"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheService creates a new instance of MockCacheService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheService {
	mock := &MockCacheService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheService is an autogenerated mock type for the CacheService type
type MockCacheService struct {
	mock.Mock
}

type MockCacheService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheService) EXPECT() *MockCacheService_Expecter {
	return &MockCacheService_Expecter{mock: &_m.Mock}
}

// GetTeamTasks provides a mock function for the type MockCacheService
func (_mock *MockCacheService) GetTeamTasks(ctx context.Context, filter *tasks_entities.TaskFilterRequest) ([]*tasks_entities.TaskResponse, int64, int64, bool, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamTasks")
	}

	var r0 []*tasks_entities.TaskResponse
	var r1 int64
	var r2 int64
	var r3 bool
	var r4 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tasks_entities.TaskFilterRequest) ([]*tasks_entities.TaskResponse, int64, int64, bool, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tasks_entities.TaskFilterRequest) []*tasks_entities.TaskResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasks_entities.TaskResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *tasks_entities.TaskFilterRequest) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *tasks_entities.TaskFilterRequest) int64); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Get(2).(int64)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, *tasks_entities.TaskFilterRequest) bool); ok {
		r3 = returnFunc(ctx, filter)
	} else {
		r3 = ret.Get(3).(bool)
	}
	if returnFunc, ok := ret.Get(4).(func(context.Context, *tasks_entities.TaskFilterRequest) error); ok {
		r4 = returnFunc(ctx, filter)
	} else {
		r4 = ret.Error(4)
	}
	return r0, r1, r2, r3, r4
}

// MockCacheService_GetTeamTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamTasks'
type MockCacheService_GetTeamTasks_Call struct {
	*mock.Call
}

// GetTeamTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *tasks_entities.TaskFilterRequest
func (_e *MockCacheService_Expecter) GetTeamTasks(ctx interface{}, filter interface{}) *MockCacheService_GetTeamTasks_Call {
	return &MockCacheService_GetTeamTasks_Call{Call: _e.mock.On("GetTeamTasks", ctx, filter)}
}

func (_c *MockCacheService_GetTeamTasks_Call) Run(run func(ctx context.Context, filter *tasks_entities.TaskFilterRequest)) *MockCacheService_GetTeamTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tasks_entities.TaskFilterRequest
		if args[1] != nil {
			arg1 = args[1].(*tasks_entities.TaskFilterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheService_GetTeamTasks_Call) Return(tasks []*tasks_entities.TaskResponse, contentRange int64, version int64, found bool, err error) *MockCacheService_GetTeamTasks_Call {
	_c.Call.Return(tasks, contentRange, version, found, err)
	return _c
}

func (_c *MockCacheService_GetTeamTasks_Call) RunAndReturn(run func(ctx context.Context, filter *tasks_entities.TaskFilterRequest) ([]*tasks_entities.TaskResponse, int64, int64, bool, error)) *MockCacheService_GetTeamTasks_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateTeamTasks provides a mock function for the type MockCacheService
func (_mock *MockCacheService) InvalidateTeamTasks(ctx context.Context, teamID uint64) error {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateTeamTasks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheService_InvalidateTeamTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateTeamTasks'
type MockCacheService_InvalidateTeamTasks_Call struct {
	*mock.Call
}

// InvalidateTeamTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint64
func (_e *MockCacheService_Expecter) InvalidateTeamTasks(ctx interface{}, teamID interface{}) *MockCacheService_InvalidateTeamTasks_Call {
	return &MockCacheService_InvalidateTeamTasks_Call{Call: _e.mock.On("InvalidateTeamTasks", ctx, teamID)}
}

func (_c *MockCacheService_InvalidateTeamTasks_Call) Run(run func(ctx context.Context, teamID uint64)) *MockCacheService_InvalidateTeamTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheService_InvalidateTeamTasks_Call) Return(err error) *MockCacheService_InvalidateTeamTasks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheService_InvalidateTeamTasks_Call) RunAndReturn(run func(ctx context.Context, teamID uint64) error) *MockCacheService_InvalidateTeamTasks_Call {
	_c.Call.Return(run)
	return _c
}

// SetTeamTasks provides a mock function for the type MockCacheService
func (_mock *MockCacheService) SetTeamTasks(ctx context.Context, filter *tasks_entities.TaskFilterRequest, version int64, tasks []*tasks_entities.TaskResponse, contentRange int64) error {
	ret := _mock.Called(ctx, filter, version, tasks, contentRange)

	if len(ret) == 0 {
		panic("no return value specified for SetTeamTasks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tasks_entities.TaskFilterRequest, int64, []*tasks_entities.TaskResponse, int64) error); ok {
		r0 = returnFunc(ctx, filter, version, tasks, contentRange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheService_SetTeamTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTeamTasks'
type MockCacheService_SetTeamTasks_Call struct {
	*mock.Call
}

// SetTeamTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *tasks_entities.TaskFilterRequest
//   - version int64
//   - tasks []*tasks_entities.TaskResponse
//   - contentRange int64
func (_e *MockCacheService_Expecter) SetTeamTasks(ctx interface{}, filter interface{}, version interface{}, tasks interface{}, contentRange interface{}) *MockCacheService_SetTeamTasks_Call {
	return &MockCacheService_SetTeamTasks_Call{Call: _e.mock.On("SetTeamTasks", ctx, filter, version, tasks, contentRange)}
}

func (_c *MockCacheService_SetTeamTasks_Call) Run(run func(ctx context.Context, filter *tasks_entities.TaskFilterRequest, version int64, tasks []*tasks_entities.TaskResponse, contentRange int64)) *MockCacheService_SetTeamTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tasks_entities.TaskFilterRequest
		if args[1] != nil {
			arg1 = args[1].(*tasks_entities.TaskFilterRequest)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 []*tasks_entities.TaskResponse
		if args[3] != nil {
			arg3 = args[3].([]*tasks_entities.TaskResponse)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCacheService_SetTeamTasks_Call) Return(err error) *MockCacheService_SetTeamTasks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheService_SetTeamTasks_Call) RunAndReturn(run func(ctx context.Context, filter *tasks_entities.TaskFilterRequest, version int64, tasks []*tasks_entities.TaskResponse, contentRange int64) error) *MockCacheService_SetTeamTasks_Call {
	_c.Call.Return(run)
	return _c
}
