// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTransactionManager creates a new instance of MockTransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionManager {
	mock := &MockTransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionManager is an autogenerated mock type for the TransactionManager type
type MockTransactionManager struct {
	mock.Mock
}

type MockTransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionManager) EXPECT() *MockTransactionManager_Expecter {
	return &MockTransactionManager_Expecter{mock: &_m.Mock}
}

// DBRun provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) DBRun(ctx context.Context, fn func(ctx context.Context, tx *gorm.DB) error, opts ...*sql.TxOptions) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, fn, opts)
	} else {
		tmpRet = _mock.Called(ctx, fn)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DBRun")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context, tx *gorm.DB) error, ...*sql.TxOptions) error); ok {
		r0 = returnFunc(ctx, fn, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_DBRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBRun'
type MockTransactionManager_DBRun_Call struct {
	*mock.Call
}

// DBRun is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, tx *gorm.DB) error
//   - opts ...*sql.TxOptions
func (_e *MockTransactionManager_Expecter) DBRun(ctx interface{}, fn interface{}, opts ...interface{}) *MockTransactionManager_DBRun_Call {
	return &MockTransactionManager_DBRun_Call{Call: _e.mock.On("DBRun",
		append([]interface{}{ctx, fn}, opts...)...)}
}

func (_c *MockTransactionManager_DBRun_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, tx *gorm.DB) error, opts ...*sql.TxOptions)) *MockTransactionManager_DBRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, tx *gorm.DB) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, tx *gorm.DB) error)
		}
		var arg2 []*sql.TxOptions
		var variadicArgs []*sql.TxOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.TxOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTransactionManager_DBRun_Call) Return(err error) *MockTransactionManager_DBRun_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_DBRun_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, tx *gorm.DB) error, opts ...*sql.TxOptions) error) *MockTransactionManager_DBRun_Call {
	_c.Call.Return(run)
	return _c
}

// DBRunWithoutTx provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) DBRunWithoutTx(fn func(tx *gorm.DB) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for DBRunWithoutTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(tx *gorm.DB) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_DBRunWithoutTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBRunWithoutTx'
type MockTransactionManager_DBRunWithoutTx_Call struct {
	*mock.Call
}

// DBRunWithoutTx is a helper method to define mock.On call
//   - fn func(tx *gorm.DB) error
func (_e *MockTransactionManager_Expecter) DBRunWithoutTx(fn interface{}) *MockTransactionManager_DBRunWithoutTx_Call {
	return &MockTransactionManager_DBRunWithoutTx_Call{Call: _e.mock.On("DBRunWithoutTx", fn)}
}

func (_c *MockTransactionManager_DBRunWithoutTx_Call) Run(run func(fn func(tx *gorm.DB) error)) *MockTransactionManager_DBRunWithoutTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(tx *gorm.DB) error
		if args[0] != nil {
			arg0 = args[0].(func(tx *gorm.DB) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManager_DBRunWithoutTx_Call) Return(err error) *MockTransactionManager_DBRunWithoutTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_DBRunWithoutTx_Call) RunAndReturn(run func(fn func(tx *gorm.DB) error) error) *MockTransactionManager_DBRunWithoutTx_Call {
	_c.Call.Return(run)
	return _c
}

// IsInTransaction provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) IsInTransaction(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsInTransaction")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTransactionManager_IsInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInTransaction'
type MockTransactionManager_IsInTransaction_Call struct {
	*mock.Call
}

// IsInTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionManager_Expecter) IsInTransaction(ctx interface{}) *MockTransactionManager_IsInTransaction_Call {
	return &MockTransactionManager_IsInTransaction_Call{Call: _e.mock.On("IsInTransaction", ctx)}
}

func (_c *MockTransactionManager_IsInTransaction_Call) Run(run func(ctx context.Context)) *MockTransactionManager_IsInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManager_IsInTransaction_Call) Return(b bool) *MockTransactionManager_IsInTransaction_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTransactionManager_IsInTransaction_Call) RunAndReturn(run func(ctx context.Context) bool) *MockTransactionManager_IsInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Launch provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) Launch() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Launch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_Launch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Launch'
type MockTransactionManager_Launch_Call struct {
	*mock.Call
}

// Launch is a helper method to define mock.On call
func (_e *MockTransactionManager_Expecter) Launch() *MockTransactionManager_Launch_Call {
	return &MockTransactionManager_Launch_Call{Call: _e.mock.On("Launch")}
}

func (_c *MockTransactionManager_Launch_Call) Run(run func()) *MockTransactionManager_Launch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionManager_Launch_Call) Return(err error) *MockTransactionManager_Launch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_Launch_Call) RunAndReturn(run func() error) *MockTransactionManager_Launch_Call {
	_c.Call.Return(run)
	return _c
}

// Migration provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) Migration() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_Migration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migration'
type MockTransactionManager_Migration_Call struct {
	*mock.Call
}

// Migration is a helper method to define mock.On call
func (_e *MockTransactionManager_Expecter) Migration() *MockTransactionManager_Migration_Call {
	return &MockTransactionManager_Migration_Call{Call: _e.mock.On("Migration")}
}

func (_c *MockTransactionManager_Migration_Call) Run(run func()) *MockTransactionManager_Migration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionManager_Migration_Call) Return(err error) *MockTransactionManager_Migration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_Migration_Call) RunAndReturn(run func() error) *MockTransactionManager_Migration_Call {
	_c.Call.Return(run)
	return _c
}

// Recover provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) Recover() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recover")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_Recover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recover'
type MockTransactionManager_Recover_Call struct {
	*mock.Call
}

// Recover is a helper method to define mock.On call
func (_e *MockTransactionManager_Expecter) Recover() *MockTransactionManager_Recover_Call {
	return &MockTransactionManager_Recover_Call{Call: _e.mock.On("Recover")}
}

func (_c *MockTransactionManager_Recover_Call) Run(run func()) *MockTransactionManager_Recover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionManager_Recover_Call) Return(err error) *MockTransactionManager_Recover_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_Recover_Call) RunAndReturn(run func() error) *MockTransactionManager_Recover_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverMigration provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) RecoverMigration() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RecoverMigration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_RecoverMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverMigration'
type MockTransactionManager_RecoverMigration_Call struct {
	*mock.Call
}

// RecoverMigration is a helper method to define mock.On call
func (_e *MockTransactionManager_Expecter) RecoverMigration() *MockTransactionManager_RecoverMigration_Call {
	return &MockTransactionManager_RecoverMigration_Call{Call: _e.mock.On("RecoverMigration")}
}

func (_c *MockTransactionManager_RecoverMigration_Call) Run(run func()) *MockTransactionManager_RecoverMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionManager_RecoverMigration_Call) Return(err error) *MockTransactionManager_RecoverMigration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_RecoverMigration_Call) RunAndReturn(run func() error) *MockTransactionManager_RecoverMigration_Call {
	_c.Call.Return(run)
	return _c
}

// SetConnection provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) SetConnection(conn *gorm.DB) {
	_mock.Called(conn)
	return
}

// MockTransactionManager_SetConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnection'
type MockTransactionManager_SetConnection_Call struct {
	*mock.Call
}

// SetConnection is a helper method to define mock.On call
//   - conn *gorm.DB
func (_e *MockTransactionManager_Expecter) SetConnection(conn interface{}) *MockTransactionManager_SetConnection_Call {
	return &MockTransactionManager_SetConnection_Call{Call: _e.mock.On("SetConnection", conn)}
}

func (_c *MockTransactionManager_SetConnection_Call) Run(run func(conn *gorm.DB)) *MockTransactionManager_SetConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionManager_SetConnection_Call) Return() *MockTransactionManager_SetConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransactionManager_SetConnection_Call) RunAndReturn(run func(conn *gorm.DB)) *MockTransactionManager_SetConnection_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTransactionManager_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockTransactionManager_Expecter) Stop() *MockTransactionManager_Stop_Call {
	return &MockTransactionManager_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockTransactionManager_Stop_Call) Run(run func()) *MockTransactionManager_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionManager_Stop_Call) Return(err error) *MockTransactionManager_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_Stop_Call) RunAndReturn(run func() error) *MockTransactionManager_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTransactionManager
func (_mock *MockTransactionManager) Update() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockTransactionManager_Expecter) Update() *MockTransactionManager_Update_Call {
	return &MockTransactionManager_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockTransactionManager_Update_Call) Run(run func()) *MockTransactionManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionManager_Update_Call) Return(err error) *MockTransactionManager_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionManager_Update_Call) RunAndReturn(run func() error) *MockTransactionManager_Update_Call {
	_c.Call.Return(run)
	return _c
}
