// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mkk_basis/rest_api/internal/app/core/entities/tasks-entities"
	"mkk_basis/rest_api/internal/app/core/services/tasks-service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) CreateTask(ctx context.Context, userID uint64, request *tasks_entities.TaskRequest) (*tasks_entities.TaskResponse, error) {
	ret := _mock.Called(ctx, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *tasks_entities.TaskResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *tasks_entities.TaskRequest) (*tasks_entities.TaskResponse, error)); ok {
		return returnFunc(ctx, userID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *tasks_entities.TaskRequest) *tasks_entities.TaskResponse); ok {
		r0 = returnFunc(ctx, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks_entities.TaskResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *tasks_entities.TaskRequest) error); ok {
		r1 = returnFunc(ctx, userID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - request *tasks_entities.TaskRequest
func (_e *MockTaskService_Expecter) CreateTask(ctx interface{}, userID interface{}, request interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, userID, request)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(ctx context.Context, userID uint64, request *tasks_entities.TaskRequest)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *tasks_entities.TaskRequest
		if args[2] != nil {
			arg2 = args[2].(*tasks_entities.TaskRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(taskResponse *tasks_entities.TaskResponse, err error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(taskResponse, err)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(ctx context.Context, userID uint64, request *tasks_entities.TaskRequest) (*tasks_entities.TaskResponse, error)) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskHistory provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetTaskHistory(ctx context.Context, taskID uint64, userID uint64) ([]*tasks_entities.TaskHistoryResponse, error) {
	ret := _mock.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskHistory")
	}

	var r0 []*tasks_entities.TaskHistoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]*tasks_entities.TaskHistoryResponse, error)); ok {
		return returnFunc(ctx, taskID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*tasks_entities.TaskHistoryResponse); ok {
		r0 = returnFunc(ctx, taskID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasks_entities.TaskHistoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, taskID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetTaskHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskHistory'
type MockTaskService_GetTaskHistory_Call struct {
	*mock.Call
}

// GetTaskHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uint64
//   - userID uint64
func (_e *MockTaskService_Expecter) GetTaskHistory(ctx interface{}, taskID interface{}, userID interface{}) *MockTaskService_GetTaskHistory_Call {
	return &MockTaskService_GetTaskHistory_Call{Call: _e.mock.On("GetTaskHistory", ctx, taskID, userID)}
}

func (_c *MockTaskService_GetTaskHistory_Call) Run(run func(ctx context.Context, taskID uint64, userID uint64)) *MockTaskService_GetTaskHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_GetTaskHistory_Call) Return(taskHistoryResponses []*tasks_entities.TaskHistoryResponse, err error) *MockTaskService_GetTaskHistory_Call {
	_c.Call.Return(taskHistoryResponses, err)
	return _c
}

func (_c *MockTaskService_GetTaskHistory_Call) RunAndReturn(run func(ctx context.Context, taskID uint64, userID uint64) ([]*tasks_entities.TaskHistoryResponse, error)) *MockTaskService_GetTaskHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetTasks(ctx context.Context, userID uint64, params *tasks_entities.TaskFilterRequest) (*tasks_service.FoundTasksResponse, error) {
	ret := _mock.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 *tasks_service.FoundTasksResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *tasks_entities.TaskFilterRequest) (*tasks_service.FoundTasksResponse, error)); ok {
		return returnFunc(ctx, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *tasks_entities.TaskFilterRequest) *tasks_service.FoundTasksResponse); ok {
		r0 = returnFunc(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks_service.FoundTasksResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *tasks_entities.TaskFilterRequest) error); ok {
		r1 = returnFunc(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTaskService_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - params *tasks_entities.TaskFilterRequest
func (_e *MockTaskService_Expecter) GetTasks(ctx interface{}, userID interface{}, params interface{}) *MockTaskService_GetTasks_Call {
	return &MockTaskService_GetTasks_Call{Call: _e.mock.On("GetTasks", ctx, userID, params)}
}

func (_c *MockTaskService_GetTasks_Call) Run(run func(ctx context.Context, userID uint64, params *tasks_entities.TaskFilterRequest)) *MockTaskService_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *tasks_entities.TaskFilterRequest
		if args[2] != nil {
			arg2 = args[2].(*tasks_entities.TaskFilterRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskService_GetTasks_Call) Return(foundTasksResponse *tasks_service.FoundTasksResponse, err error) *MockTaskService_GetTasks_Call {
	_c.Call.Return(foundTasksResponse, err)
	return _c
}

func (_c *MockTaskService_GetTasks_Call) RunAndReturn(run func(ctx context.Context, userID uint64, params *tasks_entities.TaskFilterRequest) (*tasks_service.FoundTasksResponse, error)) *MockTaskService_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksWithAssigneeOutsideTeam provides a mock function for the type MockTaskService
func (_mock *MockTaskService) GetTasksWithAssigneeOutsideTeam(ctx context.Context) ([]*tasks_entities.TaskResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksWithAssigneeOutsideTeam")
	}

	var r0 []*tasks_entities.TaskResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*tasks_entities.TaskResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*tasks_entities.TaskResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasks_entities.TaskResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_GetTasksWithAssigneeOutsideTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksWithAssigneeOutsideTeam'
type MockTaskService_GetTasksWithAssigneeOutsideTeam_Call struct {
	*mock.Call
}

// GetTasksWithAssigneeOutsideTeam is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) GetTasksWithAssigneeOutsideTeam(ctx interface{}) *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call {
	return &MockTaskService_GetTasksWithAssigneeOutsideTeam_Call{Call: _e.mock.On("GetTasksWithAssigneeOutsideTeam", ctx)}
}

func (_c *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call) Run(run func(ctx context.Context)) *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call) Return(taskResponses []*tasks_entities.TaskResponse, err error) *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call {
	_c.Call.Return(taskResponses, err)
	return _c
}

func (_c *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call) RunAndReturn(run func(ctx context.Context) ([]*tasks_entities.TaskResponse, error)) *MockTaskService_GetTasksWithAssigneeOutsideTeam_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type MockTaskService
func (_mock *MockTaskService) UpdateTask(ctx context.Context, taskID uint64, userID uint64, request *tasks_entities.TaskRequest) (*tasks_entities.TaskResponse, error) {
	ret := _mock.Called(ctx, taskID, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *tasks_entities.TaskResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, *tasks_entities.TaskRequest) (*tasks_entities.TaskResponse, error)); ok {
		return returnFunc(ctx, taskID, userID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, *tasks_entities.TaskRequest) *tasks_entities.TaskResponse); ok {
		r0 = returnFunc(ctx, taskID, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks_entities.TaskResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, *tasks_entities.TaskRequest) error); ok {
		r1 = returnFunc(ctx, taskID, userID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID uint64
//   - userID uint64
//   - request *tasks_entities.TaskRequest
func (_e *MockTaskService_Expecter) UpdateTask(ctx interface{}, taskID interface{}, userID interface{}, request interface{}) *MockTaskService_UpdateTask_Call {
	return &MockTaskService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, taskID, userID, request)}
}

func (_c *MockTaskService_UpdateTask_Call) Run(run func(ctx context.Context, taskID uint64, userID uint64, request *tasks_entities.TaskRequest)) *MockTaskService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 *tasks_entities.TaskRequest
		if args[3] != nil {
			arg3 = args[3].(*tasks_entities.TaskRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) Return(taskResponse *tasks_entities.TaskResponse, err error) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(taskResponse, err)
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) RunAndReturn(run func(ctx context.Context, taskID uint64, userID uint64, request *tasks_entities.TaskRequest) (*tasks_entities.TaskResponse, error)) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
