// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mkk_basis/rest_api/internal/app/core/repositorys/task-history"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTaskHistoryRepository creates a new instance of MockTaskHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskHistoryRepository {
	mock := &MockTaskHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskHistoryRepository is an autogenerated mock type for the TaskHistoryRepository type
type MockTaskHistoryRepository struct {
	mock.Mock
}

type MockTaskHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskHistoryRepository) EXPECT() *MockTaskHistoryRepository_Expecter {
	return &MockTaskHistoryRepository_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function for the type MockTaskHistoryRepository
func (_mock *MockTaskHistoryRepository) CreateBatch(models []*task_history.TaskHistoryModel, dbConn *gorm.DB) ([]*task_history.TaskHistoryModel, error) {
	ret := _mock.Called(models, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []*task_history.TaskHistoryModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*task_history.TaskHistoryModel, *gorm.DB) ([]*task_history.TaskHistoryModel, error)); ok {
		return returnFunc(models, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func([]*task_history.TaskHistoryModel, *gorm.DB) []*task_history.TaskHistoryModel); ok {
		r0 = returnFunc(models, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task_history.TaskHistoryModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*task_history.TaskHistoryModel, *gorm.DB) error); ok {
		r1 = returnFunc(models, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskHistoryRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockTaskHistoryRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - models []*task_history.TaskHistoryModel
//   - dbConn *gorm.DB
func (_e *MockTaskHistoryRepository_Expecter) CreateBatch(models interface{}, dbConn interface{}) *MockTaskHistoryRepository_CreateBatch_Call {
	return &MockTaskHistoryRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", models, dbConn)}
}

func (_c *MockTaskHistoryRepository_CreateBatch_Call) Run(run func(models []*task_history.TaskHistoryModel, dbConn *gorm.DB)) *MockTaskHistoryRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*task_history.TaskHistoryModel
		if args[0] != nil {
			arg0 = args[0].([]*task_history.TaskHistoryModel)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskHistoryRepository_CreateBatch_Call) Return(taskHistoryModels []*task_history.TaskHistoryModel, err error) *MockTaskHistoryRepository_CreateBatch_Call {
	_c.Call.Return(taskHistoryModels, err)
	return _c
}

func (_c *MockTaskHistoryRepository_CreateBatch_Call) RunAndReturn(run func(models []*task_history.TaskHistoryModel, dbConn *gorm.DB) ([]*task_history.TaskHistoryModel, error)) *MockTaskHistoryRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByTaskID provides a mock function for the type MockTaskHistoryRepository
func (_mock *MockTaskHistoryRepository) FindAllByTaskID(taskID uint64, dbConn *gorm.DB) ([]*task_history.TaskHistoryModel, error) {
	ret := _mock.Called(taskID, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByTaskID")
	}

	var r0 []*task_history.TaskHistoryModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) ([]*task_history.TaskHistoryModel, error)); ok {
		return returnFunc(taskID, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) []*task_history.TaskHistoryModel); ok {
		r0 = returnFunc(taskID, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task_history.TaskHistoryModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(taskID, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskHistoryRepository_FindAllByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByTaskID'
type MockTaskHistoryRepository_FindAllByTaskID_Call struct {
	*mock.Call
}

// FindAllByTaskID is a helper method to define mock.On call
//   - taskID uint64
//   - dbConn *gorm.DB
func (_e *MockTaskHistoryRepository_Expecter) FindAllByTaskID(taskID interface{}, dbConn interface{}) *MockTaskHistoryRepository_FindAllByTaskID_Call {
	return &MockTaskHistoryRepository_FindAllByTaskID_Call{Call: _e.mock.On("FindAllByTaskID", taskID, dbConn)}
}

func (_c *MockTaskHistoryRepository_FindAllByTaskID_Call) Run(run func(taskID uint64, dbConn *gorm.DB)) *MockTaskHistoryRepository_FindAllByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskHistoryRepository_FindAllByTaskID_Call) Return(taskHistoryModels []*task_history.TaskHistoryModel, err error) *MockTaskHistoryRepository_FindAllByTaskID_Call {
	_c.Call.Return(taskHistoryModels, err)
	return _c
}

func (_c *MockTaskHistoryRepository_FindAllByTaskID_Call) RunAndReturn(run func(taskID uint64, dbConn *gorm.DB) ([]*task_history.TaskHistoryModel, error)) *MockTaskHistoryRepository_FindAllByTaskID_Call {
	_c.Call.Return(run)
	return _c
}
