// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mkk_basis/rest_api/internal/app/core/entities/tasks-entities"
	"mkk_basis/rest_api/internal/app/core/repositorys/tasks"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(model *tasks.TaskModel, dbConn *gorm.DB) (*tasks.TaskModel, error) {
	ret := _mock.Called(model, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tasks.TaskModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*tasks.TaskModel, *gorm.DB) (*tasks.TaskModel, error)); ok {
		return returnFunc(model, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*tasks.TaskModel, *gorm.DB) *tasks.TaskModel); ok {
		r0 = returnFunc(model, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.TaskModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*tasks.TaskModel, *gorm.DB) error); ok {
		r1 = returnFunc(model, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - model *tasks.TaskModel
//   - dbConn *gorm.DB
func (_e *MockTaskRepository_Expecter) Create(model interface{}, dbConn interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", model, dbConn)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(model *tasks.TaskModel, dbConn *gorm.DB)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tasks.TaskModel
		if args[0] != nil {
			arg0 = args[0].(*tasks.TaskModel)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(taskModel *tasks.TaskModel, err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(taskModel, err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(model *tasks.TaskModel, dbConn *gorm.DB) (*tasks.TaskModel, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithAssigneeOutsideTeam provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindAllWithAssigneeOutsideTeam(dbConn *gorm.DB) ([]*tasks.TaskModel, error) {
	ret := _mock.Called(dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithAssigneeOutsideTeam")
	}

	var r0 []*tasks.TaskModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) ([]*tasks.TaskModel, error)); ok {
		return returnFunc(dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) []*tasks.TaskModel); ok {
		r0 = returnFunc(dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasks.TaskModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = returnFunc(dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithAssigneeOutsideTeam'
type MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call struct {
	*mock.Call
}

// FindAllWithAssigneeOutsideTeam is a helper method to define mock.On call
//   - dbConn *gorm.DB
func (_e *MockTaskRepository_Expecter) FindAllWithAssigneeOutsideTeam(dbConn interface{}) *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call {
	return &MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call{Call: _e.mock.On("FindAllWithAssigneeOutsideTeam", dbConn)}
}

func (_c *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call) Run(run func(dbConn *gorm.DB)) *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call) Return(taskModels []*tasks.TaskModel, err error) *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call {
	_c.Call.Return(taskModels, err)
	return _c
}

func (_c *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call) RunAndReturn(run func(dbConn *gorm.DB) ([]*tasks.TaskModel, error)) *MockTaskRepository_FindAllWithAssigneeOutsideTeam_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithFilter provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindAllWithFilter(params *tasks_entities.TaskFilterRequest, dbConn *gorm.DB) (*tasks.FoundTasks, error) {
	ret := _mock.Called(params, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithFilter")
	}

	var r0 *tasks.FoundTasks
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*tasks_entities.TaskFilterRequest, *gorm.DB) (*tasks.FoundTasks, error)); ok {
		return returnFunc(params, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*tasks_entities.TaskFilterRequest, *gorm.DB) *tasks.FoundTasks); ok {
		r0 = returnFunc(params, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.FoundTasks)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*tasks_entities.TaskFilterRequest, *gorm.DB) error); ok {
		r1 = returnFunc(params, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_FindAllWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithFilter'
type MockTaskRepository_FindAllWithFilter_Call struct {
	*mock.Call
}

// FindAllWithFilter is a helper method to define mock.On call
//   - params *tasks_entities.TaskFilterRequest
//   - dbConn *gorm.DB
func (_e *MockTaskRepository_Expecter) FindAllWithFilter(params interface{}, dbConn interface{}) *MockTaskRepository_FindAllWithFilter_Call {
	return &MockTaskRepository_FindAllWithFilter_Call{Call: _e.mock.On("FindAllWithFilter", params, dbConn)}
}

func (_c *MockTaskRepository_FindAllWithFilter_Call) Run(run func(params *tasks_entities.TaskFilterRequest, dbConn *gorm.DB)) *MockTaskRepository_FindAllWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tasks_entities.TaskFilterRequest
		if args[0] != nil {
			arg0 = args[0].(*tasks_entities.TaskFilterRequest)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindAllWithFilter_Call) Return(foundTasks *tasks.FoundTasks, err error) *MockTaskRepository_FindAllWithFilter_Call {
	_c.Call.Return(foundTasks, err)
	return _c
}

func (_c *MockTaskRepository_FindAllWithFilter_Call) RunAndReturn(run func(params *tasks_entities.TaskFilterRequest, dbConn *gorm.DB) (*tasks.FoundTasks, error)) *MockTaskRepository_FindAllWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindByID(id uint64, dbConn *gorm.DB) (*tasks.TaskModel, error) {
	ret := _mock.Called(id, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *tasks.TaskModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) (*tasks.TaskModel, error)); ok {
		return returnFunc(id, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) *tasks.TaskModel); ok {
		r0 = returnFunc(id, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.TaskModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(id, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTaskRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
//   - dbConn *gorm.DB
func (_e *MockTaskRepository_Expecter) FindByID(id interface{}, dbConn interface{}) *MockTaskRepository_FindByID_Call {
	return &MockTaskRepository_FindByID_Call{Call: _e.mock.On("FindByID", id, dbConn)}
}

func (_c *MockTaskRepository_FindByID_Call) Run(run func(id uint64, dbConn *gorm.DB)) *MockTaskRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindByID_Call) Return(taskModel *tasks.TaskModel, err error) *MockTaskRepository_FindByID_Call {
	_c.Call.Return(taskModel, err)
	return _c
}

func (_c *MockTaskRepository_FindByID_Call) RunAndReturn(run func(id uint64, dbConn *gorm.DB) (*tasks.TaskModel, error)) *MockTaskRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(id uint64, values map[string]interface{}, dbConn *gorm.DB) (*tasks.TaskModel, error) {
	ret := _mock.Called(id, values, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *tasks.TaskModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, map[string]interface{}, *gorm.DB) (*tasks.TaskModel, error)); ok {
		return returnFunc(id, values, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, map[string]interface{}, *gorm.DB) *tasks.TaskModel); ok {
		r0 = returnFunc(id, values, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasks.TaskModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, map[string]interface{}, *gorm.DB) error); ok {
		r1 = returnFunc(id, values, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint64
//   - values map[string]interface{}
//   - dbConn *gorm.DB
func (_e *MockTaskRepository_Expecter) Update(id interface{}, values interface{}, dbConn interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", id, values, dbConn)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(id uint64, values map[string]interface{}, dbConn *gorm.DB)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(taskModel *tasks.TaskModel, err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(taskModel, err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(id uint64, values map[string]interface{}, dbConn *gorm.DB) (*tasks.TaskModel, error)) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
