// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mkk_basis/rest_api/internal/app/core/repositorys/task-comments"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTaskCommentRepository creates a new instance of MockTaskCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCommentRepository {
	mock := &MockTaskCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskCommentRepository is an autogenerated mock type for the TaskCommentRepository type
type MockTaskCommentRepository struct {
	mock.Mock
}

type MockTaskCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCommentRepository) EXPECT() *MockTaskCommentRepository_Expecter {
	return &MockTaskCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskCommentRepository
func (_mock *MockTaskCommentRepository) Create(model *task_comments.TaskCommentModel, dbConn *gorm.DB) (*task_comments.TaskCommentModel, error) {
	ret := _mock.Called(model, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *task_comments.TaskCommentModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*task_comments.TaskCommentModel, *gorm.DB) (*task_comments.TaskCommentModel, error)); ok {
		return returnFunc(model, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*task_comments.TaskCommentModel, *gorm.DB) *task_comments.TaskCommentModel); ok {
		r0 = returnFunc(model, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task_comments.TaskCommentModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*task_comments.TaskCommentModel, *gorm.DB) error); ok {
		r1 = returnFunc(model, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - model *task_comments.TaskCommentModel
//   - dbConn *gorm.DB
func (_e *MockTaskCommentRepository_Expecter) Create(model interface{}, dbConn interface{}) *MockTaskCommentRepository_Create_Call {
	return &MockTaskCommentRepository_Create_Call{Call: _e.mock.On("Create", model, dbConn)}
}

func (_c *MockTaskCommentRepository_Create_Call) Run(run func(model *task_comments.TaskCommentModel, dbConn *gorm.DB)) *MockTaskCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *task_comments.TaskCommentModel
		if args[0] != nil {
			arg0 = args[0].(*task_comments.TaskCommentModel)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCommentRepository_Create_Call) Return(taskCommentModel *task_comments.TaskCommentModel, err error) *MockTaskCommentRepository_Create_Call {
	_c.Call.Return(taskCommentModel, err)
	return _c
}

func (_c *MockTaskCommentRepository_Create_Call) RunAndReturn(run func(model *task_comments.TaskCommentModel, dbConn *gorm.DB) (*task_comments.TaskCommentModel, error)) *MockTaskCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskCommentRepository
func (_mock *MockTaskCommentRepository) Delete(id uint64, dbConn *gorm.DB) error {
	ret := _mock.Called(id, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) error); ok {
		r0 = returnFunc(id, dbConn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskCommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskCommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
//   - dbConn *gorm.DB
func (_e *MockTaskCommentRepository_Expecter) Delete(id interface{}, dbConn interface{}) *MockTaskCommentRepository_Delete_Call {
	return &MockTaskCommentRepository_Delete_Call{Call: _e.mock.On("Delete", id, dbConn)}
}

func (_c *MockTaskCommentRepository_Delete_Call) Run(run func(id uint64, dbConn *gorm.DB)) *MockTaskCommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCommentRepository_Delete_Call) Return(err error) *MockTaskCommentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskCommentRepository_Delete_Call) RunAndReturn(run func(id uint64, dbConn *gorm.DB) error) *MockTaskCommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByTaskID provides a mock function for the type MockTaskCommentRepository
func (_mock *MockTaskCommentRepository) FindAllByTaskID(taskID uint64, dbConn *gorm.DB) ([]*task_comments.TaskCommentModel, error) {
	ret := _mock.Called(taskID, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByTaskID")
	}

	var r0 []*task_comments.TaskCommentModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) ([]*task_comments.TaskCommentModel, error)); ok {
		return returnFunc(taskID, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) []*task_comments.TaskCommentModel); ok {
		r0 = returnFunc(taskID, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*task_comments.TaskCommentModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(taskID, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCommentRepository_FindAllByTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByTaskID'
type MockTaskCommentRepository_FindAllByTaskID_Call struct {
	*mock.Call
}

// FindAllByTaskID is a helper method to define mock.On call
//   - taskID uint64
//   - dbConn *gorm.DB
func (_e *MockTaskCommentRepository_Expecter) FindAllByTaskID(taskID interface{}, dbConn interface{}) *MockTaskCommentRepository_FindAllByTaskID_Call {
	return &MockTaskCommentRepository_FindAllByTaskID_Call{Call: _e.mock.On("FindAllByTaskID", taskID, dbConn)}
}

func (_c *MockTaskCommentRepository_FindAllByTaskID_Call) Run(run func(taskID uint64, dbConn *gorm.DB)) *MockTaskCommentRepository_FindAllByTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCommentRepository_FindAllByTaskID_Call) Return(taskCommentModels []*task_comments.TaskCommentModel, err error) *MockTaskCommentRepository_FindAllByTaskID_Call {
	_c.Call.Return(taskCommentModels, err)
	return _c
}

func (_c *MockTaskCommentRepository_FindAllByTaskID_Call) RunAndReturn(run func(taskID uint64, dbConn *gorm.DB) ([]*task_comments.TaskCommentModel, error)) *MockTaskCommentRepository_FindAllByTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTaskCommentRepository
func (_mock *MockTaskCommentRepository) FindByID(id uint64, dbConn *gorm.DB) (*task_comments.TaskCommentModel, error) {
	ret := _mock.Called(id, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *task_comments.TaskCommentModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) (*task_comments.TaskCommentModel, error)); ok {
		return returnFunc(id, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) *task_comments.TaskCommentModel); ok {
		r0 = returnFunc(id, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task_comments.TaskCommentModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(id, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCommentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTaskCommentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
//   - dbConn *gorm.DB
func (_e *MockTaskCommentRepository_Expecter) FindByID(id interface{}, dbConn interface{}) *MockTaskCommentRepository_FindByID_Call {
	return &MockTaskCommentRepository_FindByID_Call{Call: _e.mock.On("FindByID", id, dbConn)}
}

func (_c *MockTaskCommentRepository_FindByID_Call) Run(run func(id uint64, dbConn *gorm.DB)) *MockTaskCommentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCommentRepository_FindByID_Call) Return(taskCommentModel *task_comments.TaskCommentModel, err error) *MockTaskCommentRepository_FindByID_Call {
	_c.Call.Return(taskCommentModel, err)
	return _c
}

func (_c *MockTaskCommentRepository_FindByID_Call) RunAndReturn(run func(id uint64, dbConn *gorm.DB) (*task_comments.TaskCommentModel, error)) *MockTaskCommentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskCommentRepository
func (_mock *MockTaskCommentRepository) Update(id uint64, body string, dbConn *gorm.DB) (*task_comments.TaskCommentModel, error) {
	ret := _mock.Called(id, body, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *task_comments.TaskCommentModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string, *gorm.DB) (*task_comments.TaskCommentModel, error)); ok {
		return returnFunc(id, body, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, string, *gorm.DB) *task_comments.TaskCommentModel); ok {
		r0 = returnFunc(id, body, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task_comments.TaskCommentModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, string, *gorm.DB) error); ok {
		r1 = returnFunc(id, body, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskCommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskCommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint64
//   - body string
//   - dbConn *gorm.DB
func (_e *MockTaskCommentRepository_Expecter) Update(id interface{}, body interface{}, dbConn interface{}) *MockTaskCommentRepository_Update_Call {
	return &MockTaskCommentRepository_Update_Call{Call: _e.mock.On("Update", id, body, dbConn)}
}

func (_c *MockTaskCommentRepository_Update_Call) Run(run func(id uint64, body string, dbConn *gorm.DB)) *MockTaskCommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskCommentRepository_Update_Call) Return(taskCommentModel *task_comments.TaskCommentModel, err error) *MockTaskCommentRepository_Update_Call {
	_c.Call.Return(taskCommentModel, err)
	return _c
}

func (_c *MockTaskCommentRepository_Update_Call) RunAndReturn(run func(id uint64, body string, dbConn *gorm.DB) (*task_comments.TaskCommentModel, error)) *MockTaskCommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
