// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	teams_entities "mkk_basis/rest_api/internal/app/core/entities/teams-entities"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamService creates a new instance of MockTeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamService {
	mock := &MockTeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamService is an autogenerated mock type for the TeamService type
type MockTeamService struct {
	mock.Mock
}

type MockTeamService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamService) EXPECT() *MockTeamService_Expecter {
	return &MockTeamService_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function for the type MockTeamService
func (_mock *MockTeamService) CreateTeam(ctx context.Context, ownerID uint64, request *teams_entities.CreateTeamRequest) (*teams_entities.TeamResponse, error) {
	ret := _mock.Called(ctx, ownerID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *teams_entities.TeamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *teams_entities.CreateTeamRequest) (*teams_entities.TeamResponse, error)); ok {
		return returnFunc(ctx, ownerID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *teams_entities.CreateTeamRequest) *teams_entities.TeamResponse); ok {
		r0 = returnFunc(ctx, ownerID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teams_entities.TeamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *teams_entities.CreateTeamRequest) error); ok {
		r1 = returnFunc(ctx, ownerID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamService_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID uint64
//   - request *teams_entities.CreateTeamRequest
func (_e *MockTeamService_Expecter) CreateTeam(ctx interface{}, ownerID interface{}, request interface{}) *MockTeamService_CreateTeam_Call {
	return &MockTeamService_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, ownerID, request)}
}

func (_c *MockTeamService_CreateTeam_Call) Run(run func(ctx context.Context, ownerID uint64, request *teams_entities.CreateTeamRequest)) *MockTeamService_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *teams_entities.CreateTeamRequest
		if args[2] != nil {
			arg2 = args[2].(*teams_entities.CreateTeamRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamService_CreateTeam_Call) Return(teamResponse *teams_entities.TeamResponse, err error) *MockTeamService_CreateTeam_Call {
	_c.Call.Return(teamResponse, err)
	return _c
}

func (_c *MockTeamService_CreateTeam_Call) RunAndReturn(run func(ctx context.Context, ownerID uint64, request *teams_entities.CreateTeamRequest) (*teams_entities.TeamResponse, error)) *MockTeamService_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamStats provides a mock function for the type MockTeamService
func (_mock *MockTeamService) GetTeamStats(ctx context.Context) ([]*teams_entities.TeamStatsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamStats")
	}

	var r0 []*teams_entities.TeamStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*teams_entities.TeamStatsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*teams_entities.TeamStatsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*teams_entities.TeamStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_GetTeamStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamStats'
type MockTeamService_GetTeamStats_Call struct {
	*mock.Call
}

// GetTeamStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamService_Expecter) GetTeamStats(ctx interface{}) *MockTeamService_GetTeamStats_Call {
	return &MockTeamService_GetTeamStats_Call{Call: _e.mock.On("GetTeamStats", ctx)}
}

func (_c *MockTeamService_GetTeamStats_Call) Run(run func(ctx context.Context)) *MockTeamService_GetTeamStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamService_GetTeamStats_Call) Return(teamStatsResponses []*teams_entities.TeamStatsResponse, err error) *MockTeamService_GetTeamStats_Call {
	_c.Call.Return(teamStatsResponses, err)
	return _c
}

func (_c *MockTeamService_GetTeamStats_Call) RunAndReturn(run func(ctx context.Context) ([]*teams_entities.TeamStatsResponse, error)) *MockTeamService_GetTeamStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTeams provides a mock function for the type MockTeamService
func (_mock *MockTeamService) GetUserTeams(ctx context.Context, userID uint64) ([]*teams_entities.TeamResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeams")
	}

	var r0 []*teams_entities.TeamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]*teams_entities.TeamResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []*teams_entities.TeamResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*teams_entities.TeamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_GetUserTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTeams'
type MockTeamService_GetUserTeams_Call struct {
	*mock.Call
}

// GetUserTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockTeamService_Expecter) GetUserTeams(ctx interface{}, userID interface{}) *MockTeamService_GetUserTeams_Call {
	return &MockTeamService_GetUserTeams_Call{Call: _e.mock.On("GetUserTeams", ctx, userID)}
}

func (_c *MockTeamService_GetUserTeams_Call) Run(run func(ctx context.Context, userID uint64)) *MockTeamService_GetUserTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamService_GetUserTeams_Call) Return(teamResponses []*teams_entities.TeamResponse, err error) *MockTeamService_GetUserTeams_Call {
	_c.Call.Return(teamResponses, err)
	return _c
}

func (_c *MockTeamService_GetUserTeams_Call) RunAndReturn(run func(ctx context.Context, userID uint64) ([]*teams_entities.TeamResponse, error)) *MockTeamService_GetUserTeams_Call {
	_c.Call.Return(run)
	return _c
}

// InviteUser provides a mock function for the type MockTeamService
func (_mock *MockTeamService) InviteUser(ctx context.Context, teamID uint64, inviterID uint64, request *teams_entities.InviteUserRequest) (*teams_entities.TeamMemberResponse, error) {
	ret := _mock.Called(ctx, teamID, inviterID, request)

	if len(ret) == 0 {
		panic("no return value specified for InviteUser")
	}

	var r0 *teams_entities.TeamMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, *teams_entities.InviteUserRequest) (*teams_entities.TeamMemberResponse, error)); ok {
		return returnFunc(ctx, teamID, inviterID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64, *teams_entities.InviteUserRequest) *teams_entities.TeamMemberResponse); ok {
		r0 = returnFunc(ctx, teamID, inviterID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teams_entities.TeamMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64, *teams_entities.InviteUserRequest) error); ok {
		r1 = returnFunc(ctx, teamID, inviterID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamService_InviteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUser'
type MockTeamService_InviteUser_Call struct {
	*mock.Call
}

// InviteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint64
//   - inviterID uint64
//   - request *teams_entities.InviteUserRequest
func (_e *MockTeamService_Expecter) InviteUser(ctx interface{}, teamID interface{}, inviterID interface{}, request interface{}) *MockTeamService_InviteUser_Call {
	return &MockTeamService_InviteUser_Call{Call: _e.mock.On("InviteUser", ctx, teamID, inviterID, request)}
}

func (_c *MockTeamService_InviteUser_Call) Run(run func(ctx context.Context, teamID uint64, inviterID uint64, request *teams_entities.InviteUserRequest)) *MockTeamService_InviteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 *teams_entities.InviteUserRequest
		if args[3] != nil {
			arg3 = args[3].(*teams_entities.InviteUserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTeamService_InviteUser_Call) Return(teamMemberResponse *teams_entities.TeamMemberResponse, err error) *MockTeamService_InviteUser_Call {
	_c.Call.Return(teamMemberResponse, err)
	return _c
}

func (_c *MockTeamService_InviteUser_Call) RunAndReturn(run func(ctx context.Context, teamID uint64, inviterID uint64, request *teams_entities.InviteUserRequest) (*teams_entities.TeamMemberResponse, error)) *MockTeamService_InviteUser_Call {
	_c.Call.Return(run)
	return _c
}
