// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mkk_basis/rest_api/internal/app/core/repositorys/teams"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Create(model *teams.TeamModel, dbConn *gorm.DB) (*teams.TeamModel, error) {
	ret := _mock.Called(model, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *teams.TeamModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*teams.TeamModel, *gorm.DB) (*teams.TeamModel, error)); ok {
		return returnFunc(model, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*teams.TeamModel, *gorm.DB) *teams.TeamModel); ok {
		r0 = returnFunc(model, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teams.TeamModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*teams.TeamModel, *gorm.DB) error); ok {
		r1 = returnFunc(model, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - model *teams.TeamModel
//   - dbConn *gorm.DB
func (_e *MockTeamRepository_Expecter) Create(model interface{}, dbConn interface{}) *MockTeamRepository_Create_Call {
	return &MockTeamRepository_Create_Call{Call: _e.mock.On("Create", model, dbConn)}
}

func (_c *MockTeamRepository_Create_Call) Run(run func(model *teams.TeamModel, dbConn *gorm.DB)) *MockTeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *teams.TeamModel
		if args[0] != nil {
			arg0 = args[0].(*teams.TeamModel)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Create_Call) Return(teamModel *teams.TeamModel, err error) *MockTeamRepository_Create_Call {
	_c.Call.Return(teamModel, err)
	return _c
}

func (_c *MockTeamRepository_Create_Call) RunAndReturn(run func(model *teams.TeamModel, dbConn *gorm.DB) (*teams.TeamModel, error)) *MockTeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) FindAllByUserID(userID uint64, dbConn *gorm.DB) ([]*teams.TeamWithRoleModel, error) {
	ret := _mock.Called(userID, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []*teams.TeamWithRoleModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) ([]*teams.TeamWithRoleModel, error)); ok {
		return returnFunc(userID, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) []*teams.TeamWithRoleModel); ok {
		r0 = returnFunc(userID, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*teams.TeamWithRoleModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(userID, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type MockTeamRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - userID uint64
//   - dbConn *gorm.DB
func (_e *MockTeamRepository_Expecter) FindAllByUserID(userID interface{}, dbConn interface{}) *MockTeamRepository_FindAllByUserID_Call {
	return &MockTeamRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", userID, dbConn)}
}

func (_c *MockTeamRepository_FindAllByUserID_Call) Run(run func(userID uint64, dbConn *gorm.DB)) *MockTeamRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_FindAllByUserID_Call) Return(teamWithRoleModels []*teams.TeamWithRoleModel, err error) *MockTeamRepository_FindAllByUserID_Call {
	_c.Call.Return(teamWithRoleModels, err)
	return _c
}

func (_c *MockTeamRepository_FindAllByUserID_Call) RunAndReturn(run func(userID uint64, dbConn *gorm.DB) ([]*teams.TeamWithRoleModel, error)) *MockTeamRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithStats provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) FindAllWithStats(dbConn *gorm.DB) ([]*teams.TeamStatsModel, error) {
	ret := _mock.Called(dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithStats")
	}

	var r0 []*teams.TeamStatsModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) ([]*teams.TeamStatsModel, error)); ok {
		return returnFunc(dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) []*teams.TeamStatsModel); ok {
		r0 = returnFunc(dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*teams.TeamStatsModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = returnFunc(dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_FindAllWithStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithStats'
type MockTeamRepository_FindAllWithStats_Call struct {
	*mock.Call
}

// FindAllWithStats is a helper method to define mock.On call
//   - dbConn *gorm.DB
func (_e *MockTeamRepository_Expecter) FindAllWithStats(dbConn interface{}) *MockTeamRepository_FindAllWithStats_Call {
	return &MockTeamRepository_FindAllWithStats_Call{Call: _e.mock.On("FindAllWithStats", dbConn)}
}

func (_c *MockTeamRepository_FindAllWithStats_Call) Run(run func(dbConn *gorm.DB)) *MockTeamRepository_FindAllWithStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamRepository_FindAllWithStats_Call) Return(teamStatsModels []*teams.TeamStatsModel, err error) *MockTeamRepository_FindAllWithStats_Call {
	_c.Call.Return(teamStatsModels, err)
	return _c
}

func (_c *MockTeamRepository_FindAllWithStats_Call) RunAndReturn(run func(dbConn *gorm.DB) ([]*teams.TeamStatsModel, error)) *MockTeamRepository_FindAllWithStats_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) FindByID(id uint64, dbConn *gorm.DB) (*teams.TeamModel, error) {
	ret := _mock.Called(id, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *teams.TeamModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) (*teams.TeamModel, error)); ok {
		return returnFunc(id, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) *teams.TeamModel); ok {
		r0 = returnFunc(id, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teams.TeamModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(id, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTeamRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
//   - dbConn *gorm.DB
func (_e *MockTeamRepository_Expecter) FindByID(id interface{}, dbConn interface{}) *MockTeamRepository_FindByID_Call {
	return &MockTeamRepository_FindByID_Call{Call: _e.mock.On("FindByID", id, dbConn)}
}

func (_c *MockTeamRepository_FindByID_Call) Run(run func(id uint64, dbConn *gorm.DB)) *MockTeamRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_FindByID_Call) Return(teamModel *teams.TeamModel, err error) *MockTeamRepository_FindByID_Call {
	_c.Call.Return(teamModel, err)
	return _c
}

func (_c *MockTeamRepository_FindByID_Call) RunAndReturn(run func(id uint64, dbConn *gorm.DB) (*teams.TeamModel, error)) *MockTeamRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
