// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mkk_basis/rest_api/internal/app/core/repositorys/team-members"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockTeamMemberRepository creates a new instance of MockTeamMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamMemberRepository {
	mock := &MockTeamMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamMemberRepository is an autogenerated mock type for the TeamMemberRepository type
type MockTeamMemberRepository struct {
	mock.Mock
}

type MockTeamMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamMemberRepository) EXPECT() *MockTeamMemberRepository_Expecter {
	return &MockTeamMemberRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTeamMemberRepository
func (_mock *MockTeamMemberRepository) Create(model *team_members.TeamMemberModel, dbConn *gorm.DB) (*team_members.TeamMemberModel, error) {
	ret := _mock.Called(model, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *team_members.TeamMemberModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*team_members.TeamMemberModel, *gorm.DB) (*team_members.TeamMemberModel, error)); ok {
		return returnFunc(model, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*team_members.TeamMemberModel, *gorm.DB) *team_members.TeamMemberModel); ok {
		r0 = returnFunc(model, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team_members.TeamMemberModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*team_members.TeamMemberModel, *gorm.DB) error); ok {
		r1 = returnFunc(model, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamMemberRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamMemberRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - model *team_members.TeamMemberModel
//   - dbConn *gorm.DB
func (_e *MockTeamMemberRepository_Expecter) Create(model interface{}, dbConn interface{}) *MockTeamMemberRepository_Create_Call {
	return &MockTeamMemberRepository_Create_Call{Call: _e.mock.On("Create", model, dbConn)}
}

func (_c *MockTeamMemberRepository_Create_Call) Run(run func(model *team_members.TeamMemberModel, dbConn *gorm.DB)) *MockTeamMemberRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *team_members.TeamMemberModel
		if args[0] != nil {
			arg0 = args[0].(*team_members.TeamMemberModel)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamMemberRepository_Create_Call) Return(teamMemberModel *team_members.TeamMemberModel, err error) *MockTeamMemberRepository_Create_Call {
	_c.Call.Return(teamMemberModel, err)
	return _c
}

func (_c *MockTeamMemberRepository_Create_Call) RunAndReturn(run func(model *team_members.TeamMemberModel, dbConn *gorm.DB) (*team_members.TeamMemberModel, error)) *MockTeamMemberRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTeamIDAndUserID provides a mock function for the type MockTeamMemberRepository
func (_mock *MockTeamMemberRepository) FindByTeamIDAndUserID(teamID uint64, userID uint64, dbConn *gorm.DB) (*team_members.TeamMemberModel, error) {
	ret := _mock.Called(teamID, userID, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindByTeamIDAndUserID")
	}

	var r0 *team_members.TeamMemberModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *gorm.DB) (*team_members.TeamMemberModel, error)); ok {
		return returnFunc(teamID, userID, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *gorm.DB) *team_members.TeamMemberModel); ok {
		r0 = returnFunc(teamID, userID, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*team_members.TeamMemberModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *gorm.DB) error); ok {
		r1 = returnFunc(teamID, userID, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamMemberRepository_FindByTeamIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTeamIDAndUserID'
type MockTeamMemberRepository_FindByTeamIDAndUserID_Call struct {
	*mock.Call
}

// FindByTeamIDAndUserID is a helper method to define mock.On call
//   - teamID uint64
//   - userID uint64
//   - dbConn *gorm.DB
func (_e *MockTeamMemberRepository_Expecter) FindByTeamIDAndUserID(teamID interface{}, userID interface{}, dbConn interface{}) *MockTeamMemberRepository_FindByTeamIDAndUserID_Call {
	return &MockTeamMemberRepository_FindByTeamIDAndUserID_Call{Call: _e.mock.On("FindByTeamIDAndUserID", teamID, userID, dbConn)}
}

func (_c *MockTeamMemberRepository_FindByTeamIDAndUserID_Call) Run(run func(teamID uint64, userID uint64, dbConn *gorm.DB)) *MockTeamMemberRepository_FindByTeamIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamMemberRepository_FindByTeamIDAndUserID_Call) Return(teamMemberModel *team_members.TeamMemberModel, err error) *MockTeamMemberRepository_FindByTeamIDAndUserID_Call {
	_c.Call.Return(teamMemberModel, err)
	return _c
}

func (_c *MockTeamMemberRepository_FindByTeamIDAndUserID_Call) RunAndReturn(run func(teamID uint64, userID uint64, dbConn *gorm.DB) (*team_members.TeamMemberModel, error)) *MockTeamMemberRepository_FindByTeamIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}
