// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"mkk_basis/rest_api/internal/app/core/entities/users-filter"
	"mkk_basis/rest_api/internal/app/core/repositorys/users"
	"time"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(model *users.UserModel, dbConn *gorm.DB) (*users.UserModel, error) {
	ret := _mock.Called(model, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *users.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*users.UserModel, *gorm.DB) (*users.UserModel, error)); ok {
		return returnFunc(model, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*users.UserModel, *gorm.DB) *users.UserModel); ok {
		r0 = returnFunc(model, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*users.UserModel, *gorm.DB) error); ok {
		r1 = returnFunc(model, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - model *users.UserModel
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) Create(model interface{}, dbConn interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", model, dbConn)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(model *users.UserModel, dbConn *gorm.DB)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *users.UserModel
		if args[0] != nil {
			arg0 = args[0].(*users.UserModel)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(userModel *users.UserModel, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(model *users.UserModel, dbConn *gorm.DB) (*users.UserModel, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Delete(id uint64, dbConn *gorm.DB) (*uint64, error) {
	ret := _mock.Called(id, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) (*uint64, error)); ok {
		return returnFunc(id, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) *uint64); ok {
		r0 = returnFunc(id, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(id, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) Delete(id interface{}, dbConn interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", id, dbConn)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(id uint64, dbConn *gorm.DB)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(v *uint64, err error) *MockUserRepository_Delete_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(id uint64, dbConn *gorm.DB) (*uint64, error)) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindAll(dbConn *gorm.DB) ([]*users.UserModel, error) {
	ret := _mock.Called(dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*users.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) ([]*users.UserModel, error)); ok {
		return returnFunc(dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) []*users.UserModel); ok {
		r0 = returnFunc(dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*users.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = returnFunc(dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) FindAll(dbConn interface{}) *MockUserRepository_FindAll_Call {
	return &MockUserRepository_FindAll_Call{Call: _e.mock.On("FindAll", dbConn)}
}

func (_c *MockUserRepository_FindAll_Call) Run(run func(dbConn *gorm.DB)) *MockUserRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindAll_Call) Return(userModels []*users.UserModel, err error) *MockUserRepository_FindAll_Call {
	_c.Call.Return(userModels, err)
	return _c
}

func (_c *MockUserRepository_FindAll_Call) RunAndReturn(run func(dbConn *gorm.DB) ([]*users.UserModel, error)) *MockUserRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithFilter provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindAllWithFilter(params *users_filter.UserFilterRequest, dbConn *gorm.DB) (*users.FoundUsers, error) {
	ret := _mock.Called(params, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithFilter")
	}

	var r0 *users.FoundUsers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*users_filter.UserFilterRequest, *gorm.DB) (*users.FoundUsers, error)); ok {
		return returnFunc(params, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(*users_filter.UserFilterRequest, *gorm.DB) *users.FoundUsers); ok {
		r0 = returnFunc(params, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.FoundUsers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*users_filter.UserFilterRequest, *gorm.DB) error); ok {
		r1 = returnFunc(params, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindAllWithFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithFilter'
type MockUserRepository_FindAllWithFilter_Call struct {
	*mock.Call
}

// FindAllWithFilter is a helper method to define mock.On call
//   - params *users_filter.UserFilterRequest
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) FindAllWithFilter(params interface{}, dbConn interface{}) *MockUserRepository_FindAllWithFilter_Call {
	return &MockUserRepository_FindAllWithFilter_Call{Call: _e.mock.On("FindAllWithFilter", params, dbConn)}
}

func (_c *MockUserRepository_FindAllWithFilter_Call) Run(run func(params *users_filter.UserFilterRequest, dbConn *gorm.DB)) *MockUserRepository_FindAllWithFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *users_filter.UserFilterRequest
		if args[0] != nil {
			arg0 = args[0].(*users_filter.UserFilterRequest)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindAllWithFilter_Call) Return(foundUsers *users.FoundUsers, err error) *MockUserRepository_FindAllWithFilter_Call {
	_c.Call.Return(foundUsers, err)
	return _c
}

func (_c *MockUserRepository_FindAllWithFilter_Call) RunAndReturn(run func(params *users_filter.UserFilterRequest, dbConn *gorm.DB) (*users.FoundUsers, error)) *MockUserRepository_FindAllWithFilter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByID(id uint64, dbConn *gorm.DB) (*users.UserModel, error) {
	ret := _mock.Called(id, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *users.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) (*users.UserModel, error)); ok {
		return returnFunc(id, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *gorm.DB) *users.UserModel); ok {
		r0 = returnFunc(id, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *gorm.DB) error); ok {
		r1 = returnFunc(id, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) FindByID(id interface{}, dbConn interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", id, dbConn)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(id uint64, dbConn *gorm.DB)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(userModel *users.UserModel, err error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(id uint64, dbConn *gorm.DB) (*users.UserModel, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByUsername(username string, dbConn *gorm.DB) (*users.UserModel, error) {
	ret := _mock.Called(username, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *users.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *gorm.DB) (*users.UserModel, error)); ok {
		return returnFunc(username, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *gorm.DB) *users.UserModel); ok {
		r0 = returnFunc(username, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *gorm.DB) error); ok {
		r1 = returnFunc(username, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) FindByUsername(username interface{}, dbConn interface{}) *MockUserRepository_FindByUsername_Call {
	return &MockUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username, dbConn)}
}

func (_c *MockUserRepository_FindByUsername_Call) Run(run func(username string, dbConn *gorm.DB)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) Return(userModel *users.UserModel, err error) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) RunAndReturn(run func(username string, dbConn *gorm.DB) (*users.UserModel, error)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindTopTaskCreatorsByTeamForMonth provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindTopTaskCreatorsByTeamForMonth(month time.Time, dbConn *gorm.DB) ([]*users.TeamTopTaskCreatorModel, error) {
	ret := _mock.Called(month, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for FindTopTaskCreatorsByTeamForMonth")
	}

	var r0 []*users.TeamTopTaskCreatorModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, *gorm.DB) ([]*users.TeamTopTaskCreatorModel, error)); ok {
		return returnFunc(month, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, *gorm.DB) []*users.TeamTopTaskCreatorModel); ok {
		r0 = returnFunc(month, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*users.TeamTopTaskCreatorModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, *gorm.DB) error); ok {
		r1 = returnFunc(month, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTopTaskCreatorsByTeamForMonth'
type MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call struct {
	*mock.Call
}

// FindTopTaskCreatorsByTeamForMonth is a helper method to define mock.On call
//   - month time.Time
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) FindTopTaskCreatorsByTeamForMonth(month interface{}, dbConn interface{}) *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call {
	return &MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call{Call: _e.mock.On("FindTopTaskCreatorsByTeamForMonth", month, dbConn)}
}

func (_c *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call) Run(run func(month time.Time, dbConn *gorm.DB)) *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call) Return(teamTopTaskCreatorModels []*users.TeamTopTaskCreatorModel, err error) *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call {
	_c.Call.Return(teamTopTaskCreatorModels, err)
	return _c
}

func (_c *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call) RunAndReturn(run func(month time.Time, dbConn *gorm.DB) ([]*users.TeamTopTaskCreatorModel, error)) *MockUserRepository_FindTopTaskCreatorsByTeamForMonth_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(id uint64, model *users.UserModel, dbConn *gorm.DB) (*users.UserModel, error) {
	ret := _mock.Called(id, model, dbConn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *users.UserModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *users.UserModel, *gorm.DB) (*users.UserModel, error)); ok {
		return returnFunc(id, model, dbConn)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *users.UserModel, *gorm.DB) *users.UserModel); ok {
		r0 = returnFunc(id, model, dbConn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.UserModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *users.UserModel, *gorm.DB) error); ok {
		r1 = returnFunc(id, model, dbConn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id uint64
//   - model *users.UserModel
//   - dbConn *gorm.DB
func (_e *MockUserRepository_Expecter) Update(id interface{}, model interface{}, dbConn interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", id, model, dbConn)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(id uint64, model *users.UserModel, dbConn *gorm.DB)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *users.UserModel
		if args[1] != nil {
			arg1 = args[1].(*users.UserModel)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(userModel *users.UserModel, err error) *MockUserRepository_Update_Call {
	_c.Call.Return(userModel, err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(id uint64, model *users.UserModel, dbConn *gorm.DB) (*users.UserModel, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
