// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mkk_basis/rest_api/internal/app/core/entities/users-entities"
	"mkk_basis/rest_api/internal/app/core/entities/users-filter"
	"mkk_basis/rest_api/internal/app/core/services/users-service"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, request *users_entities.UserRequest) (*users_entities.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *users_entities.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users_entities.UserRequest) (*users_entities.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users_entities.UserRequest) *users_entities.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *users_entities.UserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - request *users_entities.UserRequest
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, request interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, request)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, request *users_entities.UserRequest)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *users_entities.UserRequest
		if args[1] != nil {
			arg1 = args[1].(*users_entities.UserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(userResponse *users_entities.UserResponse, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, request *users_entities.UserRequest) (*users_entities.UserResponse, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserService
func (_mock *MockUserService) DeleteUser(ctx context.Context, id uint64) (*uint64, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*uint64, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *uint64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockUserService_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserService_DeleteUser_Call {
	return &MockUserService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserService_DeleteUser_Call) Run(run func(ctx context.Context, id uint64)) *MockUserService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_DeleteUser_Call) Return(v *uint64, err error) *MockUserService_DeleteUser_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUserService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*uint64, error)) *MockUserService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopTaskCreatorsByTeamForMonth provides a mock function for the type MockUserService
func (_mock *MockUserService) GetTopTaskCreatorsByTeamForMonth(ctx context.Context, month time.Time) ([]*users_entities.TeamTopTaskCreatorResponse, error) {
	ret := _mock.Called(ctx, month)

	if len(ret) == 0 {
		panic("no return value specified for GetTopTaskCreatorsByTeamForMonth")
	}

	var r0 []*users_entities.TeamTopTaskCreatorResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]*users_entities.TeamTopTaskCreatorResponse, error)); ok {
		return returnFunc(ctx, month)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []*users_entities.TeamTopTaskCreatorResponse); ok {
		r0 = returnFunc(ctx, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*users_entities.TeamTopTaskCreatorResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, month)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetTopTaskCreatorsByTeamForMonth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopTaskCreatorsByTeamForMonth'
type MockUserService_GetTopTaskCreatorsByTeamForMonth_Call struct {
	*mock.Call
}

// GetTopTaskCreatorsByTeamForMonth is a helper method to define mock.On call
//   - ctx context.Context
//   - month time.Time
func (_e *MockUserService_Expecter) GetTopTaskCreatorsByTeamForMonth(ctx interface{}, month interface{}) *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call {
	return &MockUserService_GetTopTaskCreatorsByTeamForMonth_Call{Call: _e.mock.On("GetTopTaskCreatorsByTeamForMonth", ctx, month)}
}

func (_c *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call) Run(run func(ctx context.Context, month time.Time)) *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call) Return(teamTopTaskCreatorResponses []*users_entities.TeamTopTaskCreatorResponse, err error) *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call {
	_c.Call.Return(teamTopTaskCreatorResponses, err)
	return _c
}

func (_c *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call) RunAndReturn(run func(ctx context.Context, month time.Time) ([]*users_entities.TeamTopTaskCreatorResponse, error)) *MockUserService_GetTopTaskCreatorsByTeamForMonth_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByID(ctx context.Context, id uint64) (*users_entities.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *users_entities.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*users_entities.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *users_entities.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *MockUserService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, id uint64)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(userResponse *users_entities.UserResponse, err error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uint64) (*users_entities.UserResponse, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByUsername(ctx context.Context, username string) (*users_entities.UserResponse, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *users_entities.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*users_entities.UserResponse, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *users_entities.UserResponse); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserService_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserService_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockUserService_GetUserByUsername_Call {
	return &MockUserService_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUserService_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserService_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByUsername_Call) Return(userResponse *users_entities.UserResponse, err error) *MockUserService_GetUserByUsername_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserService_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*users_entities.UserResponse, error)) *MockUserService_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUsers(ctx context.Context) ([]*users_entities.UserResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*users_entities.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*users_entities.UserResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*users_entities.UserResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserService_Expecter) GetUsers(ctx interface{}) *MockUserService_GetUsers_Call {
	return &MockUserService_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx)}
}

func (_c *MockUserService_GetUsers_Call) Run(run func(ctx context.Context)) *MockUserService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_GetUsers_Call) Return(userResponses []*users_entities.UserResponse, err error) *MockUserService_GetUsers_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockUserService_GetUsers_Call) RunAndReturn(run func(ctx context.Context) ([]*users_entities.UserResponse, error)) *MockUserService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersFilter provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUsersFilter(ctx context.Context, params *users_filter.UserFilterRequest) (*users_service.FoundUsersResponse, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersFilter")
	}

	var r0 *users_service.FoundUsersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users_filter.UserFilterRequest) (*users_service.FoundUsersResponse, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *users_filter.UserFilterRequest) *users_service.FoundUsersResponse); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_service.FoundUsersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *users_filter.UserFilterRequest) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUsersFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersFilter'
type MockUserService_GetUsersFilter_Call struct {
	*mock.Call
}

// GetUsersFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - params *users_filter.UserFilterRequest
func (_e *MockUserService_Expecter) GetUsersFilter(ctx interface{}, params interface{}) *MockUserService_GetUsersFilter_Call {
	return &MockUserService_GetUsersFilter_Call{Call: _e.mock.On("GetUsersFilter", ctx, params)}
}

func (_c *MockUserService_GetUsersFilter_Call) Run(run func(ctx context.Context, params *users_filter.UserFilterRequest)) *MockUserService_GetUsersFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *users_filter.UserFilterRequest
		if args[1] != nil {
			arg1 = args[1].(*users_filter.UserFilterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUsersFilter_Call) Return(foundUsersResponse *users_service.FoundUsersResponse, err error) *MockUserService_GetUsersFilter_Call {
	_c.Call.Return(foundUsersResponse, err)
	return _c
}

func (_c *MockUserService_GetUsersFilter_Call) RunAndReturn(run func(ctx context.Context, params *users_filter.UserFilterRequest) (*users_service.FoundUsersResponse, error)) *MockUserService_GetUsersFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateUser(ctx context.Context, id uint64, request *users_entities.UserRequest) (*users_entities.UserResponse, error) {
	ret := _mock.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *users_entities.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *users_entities.UserRequest) (*users_entities.UserResponse, error)); ok {
		return returnFunc(ctx, id, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, *users_entities.UserRequest) *users_entities.UserResponse); ok {
		r0 = returnFunc(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users_entities.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, *users_entities.UserRequest) error); ok {
		r1 = returnFunc(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - request *users_entities.UserRequest
func (_e *MockUserService_Expecter) UpdateUser(ctx interface{}, id interface{}, request interface{}) *MockUserService_UpdateUser_Call {
	return &MockUserService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, request)}
}

func (_c *MockUserService_UpdateUser_Call) Run(run func(ctx context.Context, id uint64, request *users_entities.UserRequest)) *MockUserService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *users_entities.UserRequest
		if args[2] != nil {
			arg2 = args[2].(*users_entities.UserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateUser_Call) Return(userResponse *users_entities.UserResponse, err error) *MockUserService_UpdateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, id uint64, request *users_entities.UserRequest) (*users_entities.UserResponse, error)) *MockUserService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
