all: false
dir: internal/mocks
filename: '{{.SrcPackageName}}.go'
force-file-write: true
formatter: goimports
log-level: warn
pkgname: mocks
require-template-schema-exists: false
structname: 'Mock{{.InterfaceName}}'
template: testify

packages:
  mkk_basis/rest_api/internal/app/core/repositorys/users:
    interfaces:
      UserRepository:
  mkk_basis/rest_api/internal/app/core/repositorys/teams:
    interfaces:
      TeamRepository:
  mkk_basis/rest_api/internal/app/core/repositorys/team-members:
    interfaces:
      TeamMemberRepository:
  mkk_basis/rest_api/internal/app/core/repositorys/tasks:
    interfaces:
      TaskRepository:
  mkk_basis/rest_api/internal/app/core/repositorys/task-history:
    interfaces:
      TaskHistoryRepository:
  mkk_basis/rest_api/internal/app/core/repositorys/task-comments:
    interfaces:
      TaskCommentRepository:
  mkk_basis/rest_api/internal/app/core/services/users-service:
    interfaces:
      UserService:
  mkk_basis/rest_api/internal/app/core/services/teams-service:
    interfaces:
      TeamService:
  mkk_basis/rest_api/internal/app/core/services/tasks-service:
    interfaces:
      TaskService:
  mkk_basis/rest_api/internal/app/core/services/auth-service:
    interfaces:
      AuthService:
  mkk_basis/rest_api/internal/app/core/services/cache-service:
    interfaces:
      CacheService:
  mkk_basis/rest_api/internal/app/infrastructure/database-service:
    interfaces:
      TransactionManager:
  mkk_basis/rest_api/internal/app/infrastructure/redis-service:
    interfaces:
      RedisClient:
