#include .env
.PHONY: run test test_with_logs mocks docs swagger

test:
	go test -race -count=1 -tags=integration ./api/... ./cmd/... ./internal/...

test_with_logs:
	go test -v -race -count=1 -tags=integration ./api/... ./cmd/... ./internal/...

mocks:
	go tool mockery

run:
	go run cmd/rest-api/main.go
docs: swagger

swagger:
	@echo "Generating Swagger docs..."
	@swag fmt
	@swag init -g ./cmd/rest-api/main.go -o ./api/docs --parseInternal --parseDependency --parseDepth 5
	@echo "Swagger docs generated in ./api/docs"
